Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu"
  config.vm.network :private_network, ip: "192.168.2.50"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "azure.yml"
  end

end
